server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: qwe123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 16379
      host: localhost
      password: qwe123
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug